name: MooResize
author: astolwijk
current: 0.2
category: Widgets
tags: [Resize,Image Resize]
demo: http://www.aryweb.nl/projects/MooResize
docs: http://github.com/arian/MooResize/blob/master/README.md